spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
#        driver-class-name: org.postgresql.Driver
#        url: ${LOCAL_DB_URL}
#        username: ${LOCAL_DB_USER_NAME}
#        password: ${LOCAL_DB_USER_PASSWORD}

    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

logging:
  config: classpath:log4j2.xml

jwt:
  secret: ${JWT_KEY}
  access_expire_time: ${A_EX_TIME}
  refresh_expire_time: ${R_EX_TIME}

path:
  profileImage: C://shopImages/profileImages
  noticeImage: C://shopImages/noticeImages
  boardImage: C://shopImages/boardImages