spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    #    driver-class-name: org.postgresql.Driver
    #    url: ${DB_URL}
    #    username: ${DB_USER_NAME}
    #    password: ${DB_USER_PASSWORD}

    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update

logging:
  config: classpath:log4j2.xml

path:
  profileImage: C://shopImages/profileImages
  noticeImage: C://shopImages/noticeImages
  boardImage: C://shopImages/boardImages