spring:
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - profile
              - email

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

logging:
  config: classpath:log4j2.xml

jwt:
  secret: ${JWT_KEY}
  access_expire_time: ${A_EX_TIME}
  refresh_expire_time: ${R_EX_TIME}

props:
  reset-password-url: 127.0.0.1:8080/pw

path:
  profileImage: C://shopImages/profileImages/
  noticeImage: C://shopImages/noticeImages/
  noticeTmpImage: C://shopImages/noticeImages/tmp/
  boardImage: C://shopImages/boardImages/
  boardTmpImage: C://shopImages/boardImages/tmp/