spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

logging:
  config: classpath:log4j2.xml

jwt:
  secret: ${JWT_KEY}
  access_expire_time: ${A_EX_TIME}
  refresh_expire_time: ${R_EX_TIME}

props:
  reset-password-url: 127.0.0.1:8080/pw

path:
  profileImage: /home/ubuntu/shopImages/profileImages/
  noticeImage: /home/ubuntu/shopImages/noticeImages/
  noticeTmpImage: /home/ubuntu/shopImages/noticeImages/tmp/
  boardImage: /home/ubuntu/shopImages/boardImages/
  boardTmpImage: /home/ubuntu/shopImages/boardImages/tmp/