spring:
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          naver:
            client-id: ${NAVER_OAUTH_CLIENT_ID}
            client-secret: ${NAVER_OAUTH_CLIENT_SECRET}
            redirect-uri: ${NAVER_OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            redirect-uri: ${KAKAO_OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

logging:
  config: classpath:log4j2.xml

jwt:
  secret: ${JWT_KEY}
  access_expire_time: ${A_EX_TIME}
  refresh_expire_time: ${R_EX_TIME}

props:
  reset-password-url: 127.0.0.1:8080/pw

path:
  profileImage: /home/ubuntu/shopImages/profileImages/
  noticeImage: /home/ubuntu/shopImages/noticeImages/
  noticeTmpImage: /home/ubuntu/shopImages/noticeImages/tmp/
  boardImage: /home/ubuntu/shopImages/boardImages/
  boardTmpImage: /home/ubuntu/shopImages/boardImages/tmp/