spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  config: classpath:log4j2.xml

jwt:
  secret: ${JWT_KEY}
  access_expire_time: ${A_EX_TIME}
  refresh_expire_time: ${R_EX_TIME}

path:
  profileImage: /home/ubuntu/shopImages/profileImages
  noticeImage: /home/ubuntu/shopImages/noticeImages
  boardImage: /home/ubuntu/shopImages/boardImages