name: Deploy to AWS EC2

on:
  pull_request:
    branches:
      - master          # master 브랜치에서 PR 발생 시
  workflow_dispatch:  # 수동 실행을 허용

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.EC2_HOST }}
      USER: ${{ secrets.EC2_USER }}
      DOCKER_COMPOSE_PATH: /home/ubuntu/compose/docker-compose.yml
      ENV_FILE_PATH: /home/ubuntu/.env  # .env 파일의 위치
      IMAGE_NAME: rlaalsrl9569/shop_was

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set executable permission for gradlew
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew clean build

      - name: Build Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t $IMAGE_NAME:${GITHUB_SHA} .
          docker push $IMAGE_NAME:${GITHUB_SHA}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        env:
          SHOP_WAS_TAG: ${{ github.sha }}  # shop_was 이미지의 태그를 SHA 해시로 설정
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST "
            cd $(dirname $DOCKER_COMPOSE_PATH) && \
            sudo docker-compose --env-file $ENV_FILE_PATH pull && \
            sudo docker-compose --env-file $ENV_FILE_PATH down && \
            sudo docker-compose --env-file $ENV_FILE_PATH up -d
          "
