name: Deploy to AWS EC2

on:
  pull_request:
    branches:
      - master  # master 브랜치에서 pull_request 이벤트 발생 시 실행

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.EC2_HOST }}
      USER: ${{ secrets.EC2_USER }}
      DOCKER_COMPOSE_PATH: /home/ubuntu/compose/docker-compose.yml
      IMAGE_NAME: rlaalsrl9569/shop_was

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Java 17 설정

      - name: Build project
        run: |
          ./gradlew clean build

      - name: Build Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t $IMAGE_NAME:${GITHUB_SHA} .
          docker push $IMAGE_NAME:${GITHUB_SHA}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        env:
          SHOP_WAS_TAG: ${{ github.sha }}  # 이미지 태그로 GitHub SHA 해시 사용
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST "
            export SHOP_WAS_TAG=$SHOP_WAS_TAG && \
            cd $(dirname $DOCKER_COMPOSE_PATH) && \
            docker-compose down && \
            docker-compose pull && \
            docker-compose up -d
          "
